GET http://localhost:4001/storeRoutes

###3

GET http://localhost:4001/storeRoutes/648840dd4fe456e173300d8b
###
POST http://localhost:4001/storeRoutes
Content-Type: application/json

{
    "name":"phone",
    "price":50,
    "description":"Nokia lumia"
}
###
DELETE http://localhost:4001/storeRoutes/648840dd4fe456e173300d8b

###
PATCH http://localhost:4001/storeRoutes/647db7ba6cb1e162b186cc0e
Content-Type: application/json

{
    "name":"bag",
    "price":5
}
###
GET http://localhost:4001/storeRoutes/search-filter?name=bag&price=14
###
POST http://localhost:4001/user/user-registration
Content-Type: application/json

{
    "name":"humemah",
    "email":"hj@gmail.com",
    "password":"12345678"
}
###
POST http://localhost:4001/user/login-user
Content-Type: application/json

{
    "email":"hk@gmail.com",
    "password":"12345678"
}
###
GET http://localhost:4001/user/profile


###
POST http://localhost:4001/carts/add-to-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgxYzI3MjhkYjJmNTdhMDBmNzRmYWUiLCJlbWFpbCI6ImhrQGdtYWlsLmNvbSIsImlhdCI6MTY4NjkxNjE0OCwiZXhwIjoxNjg2OTE5NzQ4fQ.iVt3DF4BwD87fLEO-WYcbuOcS1ytiWlQz3a5dT2BT4c

{
  "productName": "bag"
}

###
GET http://localhost:4001/carts