GET http://localhost:4001/storeRoutes

###3

GET http://localhost:4001/storeRoutes/647db7ba6cb1e162b186cc0e
###
POST http://localhost:4001/storeRoutes
Content-Type: application/json

{
    "name":"phone",
    "price":50,
    "description":"Nokia lumia"
}
###
DELETE http://localhost:4001/storeRoutes/647db7ba6cb1e162b186cc0e
###
PATCH http://localhost:4001/storeRoutes/647db7ba6cb1e162b186cc0e
Content-Type: application/json

{
    "name":"bag",
    "price":5
}
###
GET http://localhost:4001/storeRoutes/search-filter?name=bag&price=14
###
POST http://localhost:4001/user/user-registration
Content-Type: application/json

{
    "name":"humemah",
    "email":"hj@gmail.com",
    "password":"12345678"
}
###
POST http://localhost:4001/user/login-user
Content-Type: application/json

{
    "email":"hk@gmail.com",
    "password":"12345678"
}
###
POST http://localhost:4001/user/admin/register
Content-Type: application/json

{
    "name": "admin",
    "email":"admin@gmail.com",
    "password":"12345678"
}
####
GET http://localhost:4001/user/profile
###
POST http://localhost:4001/user/admin/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:4001/carts/add-to-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgxYzI3MjhkYjJmNTdhMDBmNzRmYWUiLCJlbWFpbCI6ImhrQGdtYWlsLmNvbSIsImlhdCI6MTY4NzQxNzg0NSwiZXhwIjoxNjg3NDIxNDQ1fQ.T3atx4JjxzNOhA0iXtLtPglYVsKdKmOlOQVx5A-TIes

{
  "productName": "bag"
}

###
GET http://localhost:4001/carts